[tool.poetry]
name = "pmc"
version = "0.1.0"
description = "Juego de gestion PMC"
[tool.poetry.dependencies]
python = "^3.10"
flask = "*"
flask-sqlalchemy = "*"
psycopg2-binary = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
